"$schema" = "./node_modules/wrangler/config-schema.json"

name = "mosoo-website"
compatibility_date = "2026-07-02"
main = "src/worker.js"

[assets]
directory = "./dist"
binding = "ASSETS"
html_handling = "drop-trailing-slash"
not_found_handling = "none"

[env.prod]
name = "mosoo-website-prod"
workers_dev = false

[[env.prod.routes]]
pattern = "mosoo.ai"
custom_domain = true
