export {
  MOSOO_API_REFERENCE_URL,
  MOSOO_BLOG_URL,
  MOSOO_DEPLOY_URL,
  MOSOO_DOCS_URL,
  MOSOO_GITHUB_URL,
  MOSOO_LICENSE_URL,
  MOSOO_RELEASES_URL,
  MOSOO_SECURITY_URL,
  MOSOO_X_URL,
} from "@/shared/config/external-links";
