import { locale } from "@/shared/locale";

const ZH_MESSAGES = {
  "Use cases": "用例",
  "Built on mosoo.": "用 mosoo 构建。",
  "Real products that publish an Agent once and let any client call it as an API. Each case ships with the repository, the live app, and the integration path.":
    "这些真实产品都把 Agent 发布一次，随后作为 API 被任何客户端调用。每个案例都附带仓库、可体验的线上应用与集成路径。",
  "Upload one avatar and get back a validated ZIP with all nine Codex pet animation states — generated by one published mosoo Agent behind a Cloudflare Worker.":
    "上传一张头像，取回包含全部九个 Codex 宠物动画状态、经校验的 ZIP——由一个已发布的 mosoo Agent 在 Cloudflare Worker 背后生成。",
  "Read the case": "查看案例",
  "The Codex Pet app: one avatar in, nine animation states out.":
    "Codex Pet 应用：一张头像进，九个动画状态出。",
  "More cases are being written up.": "更多案例正在整理中。",
  "Shipping something on mosoo? We want the next case to be yours.":
    "正在用 mosoo 构建产品？下一个案例希望就是你的。",
  "Start on mosoo Cloud": "在 mosoo Cloud 开始",
  "Use case": "用例",
  "Publish one Agent. Let any Codex call it.": "发布一个 Agent，任何 Codex 都能调用。",
  "Codex Pet shows how a workflow built in a coding IDE becomes a reusable mosoo-managed Agent exposed through an API — one uploaded avatar comes back as a validated ZIP with all nine Codex pet animation states.":
    "Codex Pet 展示了在 coding IDE 里搭好的工作流，如何变成一个由 mosoo 托管、通过 API 暴露的可复用 Agent——上传一张头像，返回包含全部九个 Codex 宠物动画状态、经校验的 ZIP。",
  "Open the live app": "打开线上应用",
  "View the repository": "查看仓库",
  "How it works": "工作方式",
  "Publish the Agent": "发布 Agent",
  "A Pet Agent with an avatar-generation skill is published on mosoo. Its environment carries the openai and pillow packages plus an OpenAI provider credential.":
    "在 mosoo 上发布一个带头像生成 skill 的 Pet Agent。它的 environment 装有 openai 与 pillow 包，并配置了 OpenAI provider 凭证。",
  "Copy the Instruction for LLM": "复制 Instruction for LLM",
  "Publishing generates an Instruction for LLM — an API contract sized for a prompt. Paste it into Codex and the integration work moves to the coding agent.":
    "发布后会生成一份 Instruction for LLM——一份提示词大小的 API 契约。把它粘贴进 Codex，集成工作就交给了 coding agent。",
  "Integrate from Codex": "由 Codex 完成集成",
  "Codex wires the mosoo Thread API into the product backend: the Worker creates a Thread with the uploaded avatar, polls the Run, and streams the finished ZIP back.":
    "Codex 把 mosoo Thread API 接入产品后端：Worker 用上传的头像创建 Thread，轮询 Run，并把生成好的 ZIP 流式返回。",
  "The request path": "请求链路",
  "The token stays in the Worker. The browser only ever sees the finished ZIP.":
    "token 始终留在 Worker 里，浏览器只会拿到生成完毕的 ZIP。",
  "Watch the 57-second demo": "观看 57 秒演示",
  "Agent as API, end to end — from publishing the Agent to the downloaded pet.":
    "Agent as API 全流程——从发布 Agent 到下载宠物。",
  "What comes out": "产出",
  "A 1536×1872 RGBA WebP atlas with nine animation rows, QA-checked in the sandbox before download.":
    "一张 1536×1872 的 RGBA WebP 图集，包含九行动画，下载前已在 sandbox 内通过 QA 校验。",
  Stack: "技术栈",
  "Build your own Agent as API.": "构建你自己的 Agent as API。",
  "Publish an Agent on mosoo, hand its Instruction for LLM to a coding agent, and ship the integration in an afternoon.":
    "在 mosoo 上发布一个 Agent，把它的 Instruction for LLM 交给 coding agent，一个下午就能完成集成上线。",
  "Read the docs": "阅读文档",
} as const;

type Message = keyof typeof ZH_MESSAGES;

const JA_MESSAGES = {
  "Use cases": "ユースケース",
  "Built on mosoo.": "mosoo でつくられたもの。",
  "Real products that publish an Agent once and let any client call it as an API. Each case ships with the repository, the live app, and the integration path.":
    "Agent を一度公開し、任意のクライアントから API として呼び出せるようにした実プロダクト。各ケースにはリポジトリ、ライブアプリ、統合の手順が付属します。",
  "Upload one avatar and get back a validated ZIP with all nine Codex pet animation states — generated by one published mosoo Agent behind a Cloudflare Worker.":
    "アバターを 1 枚アップロードすると、9 つの Codex ペットアニメーション状態を収めた検証済み ZIP が返ります。Cloudflare Worker の背後で、公開済みの mosoo Agent 1 つが生成します。",
  "Read the case": "ケースを見る",
  "The Codex Pet app: one avatar in, nine animation states out.":
    "Codex Pet アプリ：アバター 1 枚から、9 つのアニメーション状態へ。",
  "More cases are being written up.": "さらに多くのケースを準備中です。",
  "Shipping something on mosoo? We want the next case to be yours.":
    "mosoo で何かをつくっていますか？次のケースはあなたの番です。",
  "Start on mosoo Cloud": "mosoo Cloud で始める",
  "Use case": "ユースケース",
  "Publish one Agent. Let any Codex call it.":
    "Agent を一度公開すれば、どの Codex からでも呼び出せる。",
  "Codex Pet shows how a workflow built in a coding IDE becomes a reusable mosoo-managed Agent exposed through an API — one uploaded avatar comes back as a validated ZIP with all nine Codex pet animation states.":
    "Codex Pet は、coding IDE で組んだワークフローが mosoo 管理の再利用可能な Agent となり、API として公開される様子を示します。アップロードした 1 枚のアバターが、9 つの Codex ペットアニメーション状態を収めた検証済み ZIP になって返ります。",
  "Open the live app": "ライブアプリを開く",
  "View the repository": "リポジトリを見る",
  "How it works": "しくみ",
  "Publish the Agent": "Agent を公開する",
  "A Pet Agent with an avatar-generation skill is published on mosoo. Its environment carries the openai and pillow packages plus an OpenAI provider credential.":
    "アバター生成 skill を持つ Pet Agent を mosoo で公開します。environment には openai と pillow のパッケージ、OpenAI provider の資格情報を設定します。",
  "Copy the Instruction for LLM": "Instruction for LLM をコピーする",
  "Publishing generates an Instruction for LLM — an API contract sized for a prompt. Paste it into Codex and the integration work moves to the coding agent.":
    "公開すると Instruction for LLM が生成されます。プロンプトに収まるサイズの API 契約です。Codex に貼り付ければ、統合作業は coding agent の仕事になります。",
  "Integrate from Codex": "Codex から統合する",
  "Codex wires the mosoo Thread API into the product backend: the Worker creates a Thread with the uploaded avatar, polls the Run, and streams the finished ZIP back.":
    "Codex が mosoo Thread API をプロダクトのバックエンドに接続します。Worker がアップロードされたアバターで Thread を作成し、Run をポーリングして、完成した ZIP をストリーミングで返します。",
  "The request path": "リクエスト経路",
  "The token stays in the Worker. The browser only ever sees the finished ZIP.":
    "token は Worker の中に留まり、ブラウザに渡るのは完成した ZIP だけです。",
  "Watch the 57-second demo": "57 秒のデモを見る",
  "Agent as API, end to end — from publishing the Agent to the downloaded pet.":
    "Agent as API の一部始終 — Agent の公開からペットのダウンロードまで。",
  "What comes out": "得られるもの",
  "A 1536×1872 RGBA WebP atlas with nine animation rows, QA-checked in the sandbox before download.":
    "9 行のアニメーションを収めた 1536×1872 の RGBA WebP アトラス。ダウンロード前に sandbox 内で QA 済みです。",
  Stack: "スタック",
  "Build your own Agent as API.": "あなたの Agent as API をつくる。",
  "Publish an Agent on mosoo, hand its Instruction for LLM to a coding agent, and ship the integration in an afternoon.":
    "mosoo で Agent を公開し、その Instruction for LLM を coding agent に渡せば、統合は半日で出荷できます。",
  "Read the docs": "ドキュメントを読む",
} satisfies Record<Message, string>;

const MESSAGES = { zh: ZH_MESSAGES, ja: JA_MESSAGES };

export function t(message: Message): string {
  return locale === "en" ? message : MESSAGES[locale][message];
}
