import { locale } from "@/shared/locale";

const ZH_MESSAGES = {
  "Use cases": "用例",
  "Built on mosoo.": "用 mosoo 构建。",
  "Real products that publish an Agent once and let any client call it as an API. Each case ships with the repository, the live app, and the integration path.":
    "这些真实产品都把 Agent 发布一次，随后作为 API 被任何客户端调用。每个案例都附带仓库、可体验的线上应用与集成路径。",
  "Real products that use mosoo as their Agent backend. Each case shows the live product, the value mosoo provides, and the integration path.":
    "这些真实产品都使用 mosoo 作为 Agent backend。每个案例都会展示线上产品、mosoo 提供的价值与集成路径。",
  "A production fitness app where users log meals and workouts in natural language. One shared mosoo Agent turns every conversation into isolated, persistent user data.":
    "一款生产环境中的健身应用，用户可用自然语言记录饮食和训练。一个共享的 mosoo Agent 会把每次对话转化为隔离、持久的用户数据。",
  "The Go Gym dashboard after the Agent recorded a day of meals and training.":
    "Agent 记录一天的饮食和训练后的 Go Gym 仪表盘。",
  "Upload one avatar and get back a validated ZIP with all nine Codex pet animation states — generated by one published mosoo Agent behind a Cloudflare Worker.":
    "上传一张头像，取回包含全部九个 Codex 宠物动画状态、经校验的 ZIP——由一个已发布的 mosoo Agent 在 Cloudflare Worker 背后生成。",
  "Read the case": "查看案例",
  "The Codex Pet app: one avatar in, nine animation states out.":
    "Codex Pet 应用：一张头像进，九个动画状态出。",
  "More cases are being written up.": "更多案例正在整理中。",
  "Shipping something on mosoo? We want the next case to be yours.":
    "正在用 mosoo 构建产品？下一个案例希望就是你的。",
  "Start on mosoo Cloud": "在 mosoo Cloud 开始",
  "Use case": "用例",
  "Submitted by": "提交者",
  "Publish one Agent. Let any Codex call it.": "发布一个 Agent，任何 Codex 都能调用。",
  "Codex Pet shows how a workflow built in a coding IDE becomes a reusable mosoo-managed Agent exposed through an API — one uploaded avatar comes back as a validated ZIP with all nine Codex pet animation states.":
    "Codex Pet 展示了在 coding IDE 里搭好的工作流，如何变成一个由 mosoo 托管、通过 API 暴露的可复用 Agent——上传一张头像，返回包含全部九个 Codex 宠物动画状态、经校验的 ZIP。",
  "Open the live app": "打开线上应用",
  "View the repository": "查看仓库",
  "How it works": "工作方式",
  "Publish the Agent": "发布 Agent",
  "A Pet Agent with an avatar-generation skill is published on mosoo. Its environment carries the openai and pillow packages plus an OpenAI provider credential.":
    "在 mosoo 上发布一个带头像生成 skill 的 Pet Agent。它的 environment 装有 openai 与 pillow 包，并配置了 OpenAI provider 凭证。",
  "Copy the Instruction for LLM": "复制 Instruction for LLM",
  "Publishing generates an Instruction for LLM — an API contract sized for a prompt. Paste it into Codex and the integration work moves to the coding agent.":
    "发布后会生成一份 Instruction for LLM——一份提示词大小的 API 契约。把它粘贴进 Codex，集成工作就交给了 coding agent。",
  "Integrate from Codex": "由 Codex 完成集成",
  "Codex wires the mosoo Thread API into the product backend: the Worker creates a Thread with the uploaded avatar, polls the Run, and streams the finished ZIP back.":
    "Codex 把 mosoo Thread API 接入产品后端：Worker 用上传的头像创建 Thread，轮询 Run，并把生成好的 ZIP 流式返回。",
  "The request path": "请求链路",
  "The token stays in the Worker. The browser only ever sees the finished ZIP.":
    "token 始终留在 Worker 里，浏览器只会拿到生成完毕的 ZIP。",
  "Watch the 57-second demo": "观看 57 秒演示",
  "Agent as API, end to end — from publishing the Agent to the downloaded pet.":
    "Agent as API 全流程——从发布 Agent 到下载宠物。",
  "What comes out": "产出",
  "A 1536×1872 RGBA WebP atlas with nine animation rows, QA-checked in the sandbox before download.":
    "一张 1536×1872 的 RGBA WebP 图集，包含九行动画，下载前已在 sandbox 内通过 QA 校验。",
  Stack: "技术栈",
  "Build your own Agent as API.": "构建你自己的 Agent as API。",
  "Publish an Agent on mosoo, hand its Instruction for LLM to a coding agent, and ship the integration in an afternoon.":
    "在 mosoo 上发布一个 Agent，把它的 Instruction for LLM 交给 coding agent，一个下午就能完成集成上线。",
  "Read the docs": "阅读文档",
  "One Agent for every user. Their data stays isolated.":
    "一个 Agent 服务所有用户，数据彼此隔离。",
  "Go Gym is a production fitness tracker. Users describe meals, workouts, and body measurements in chat; the app turns them into structured records, durable dashboards, and progress summaries.":
    "Go Gym 是一款生产环境中的健身追踪应用。用户在对话中描述饮食、训练和身体指标，应用会把它们转化为结构化记录、持久仪表盘和进度总结。",
  "Read the API docs": "阅读 API 文档",
  "One Agent, user-scoped Threads": "一个 Agent，按用户划分 Thread",
  "Go Gym publishes one shared Agent. Its trusted backend creates a separate Thread with userId for each signed-in user, so the browser never receives a mosoo token.":
    "Go Gym 发布一个共享 Agent。可信后端为每位登录用户以 userId 创建独立 Thread，因此浏览器永远不会拿到 mosoo token。",
  "Delegated tool identity": "委托工具身份",
  "Mosoo carries the verified user context into the MCP call. The model cannot choose another user ID, while Go Gym and Supabase still enforce authorization at the data boundary.":
    "Mosoo 把经过验证的用户上下文带入 MCP 调用。模型无法选择其他用户 ID，同时 Go Gym 与 Supabase 仍在数据边界执行授权。",
  "Isolated, harness-neutral execution": "隔离且不绑定 harness 的执行",
  "Each Thread runs in a Cattle sandbox. Production uses OpenCode, while the same business MCP path was verified with Codex and Claude without rewriting the app.":
    "每个 Thread 都运行在 Cattle sandbox 中。生产环境使用 OpenCode，同一条业务 MCP 链路也已用 Codex 和 Claude 验证，无需重写应用。",
  "Production smoke test": "生产 smoke test",
  "From one message to durable records": "从一条消息到持久记录",
  "A test user described breakfast, lunch, and 45 minutes of strength training in one message. The Agent created three user-scoped records and refreshed the dashboard.":
    "测试用户在一条消息里描述了早餐、午餐和 45 分钟力量训练。Agent 创建了三条用户范围内的记录，并刷新了仪表盘。",
  "Verified result": "验证结果",
  "3 structured records": "3 条结构化记录",
  "1,150 kcal intake": "摄入 1,150 千卡",
  "64 g protein": "64 克蛋白质",
  "320 kcal training burn": "训练消耗 320 千卡",
  "What mosoo provides": "mosoo 提供什么",
  "The production request path": "生产请求链路",
  "The app and Agent runtime are deployed separately. The browser talks only to Go Gym; its backend holds the Mosoo token and supplies the trusted userId.":
    "应用与 Agent runtime 分开部署。浏览器只与 Go Gym 通信；后端保存 Mosoo token，并提供可信的 userId。",
  "Mosoo delegates identity; it does not replace application authorization. Go Gym validates the caller and Supabase RLS remains the final data boundary.":
    "Mosoo 负责委托身份，但不替代应用授权。Go Gym 验证调用方，Supabase RLS 仍是最终的数据边界。",
  "Clear ownership across the stack": "技术栈职责边界",
  "Product UI, Supabase login, domain rules, WebSocket updates, and the business tool endpoints.":
    "产品 UI、Supabase 登录、领域规则、WebSocket 更新和业务工具端点。",
  "Agent publication, Thread and Run lifecycle, user delegation, sandbox isolation, and harness selection.":
    "Agent 发布、Thread 与 Run 生命周期、用户委托、sandbox 隔离和 harness 选择。",
  "OAuth identity, Postgres persistence, Row Level Security, and private file storage.":
    "OAuth 身份、Postgres 持久化、Row Level Security 和私有文件存储。",
  "A stateless Container for the web app and a Worker for the remote MCP service. Durable user data stays in Supabase.":
    "用无状态 Container 承载 Web 应用，用 Worker 承载远程 MCP 服务。持久用户数据保存在 Supabase。",
  "One use case, multiple harnesses": "一个用例，多种 harness",
  "Go Gym runs on OpenCode in production. The same Agent contract and business MCP were also exercised through Codex and Claude before release.":
    "Go Gym 在生产环境运行于 OpenCode。同一份 Agent 契约和业务 MCP 在发布前也通过 Codex 与 Claude 完成了验证。",
  "Published Go Gym Agents for OpenCode, Codex, and Claude in the Mosoo console.":
    "Mosoo 控制台中为 OpenCode、Codex 和 Claude 发布的 Go Gym Agent。",
  "Explore the product and stack": "探索产品与技术栈",
  "Use the production app and try a meal or workout log.":
    "使用生产应用，尝试记录一顿饭或一次训练。",
  "Try Go Gym": "体验 Go Gym",
  "Create Threads and Runs from an application backend.":
    "从应用后端创建 Thread 与 Run。",
  "Thread API reference": "Thread API 参考",
  "Inspect the open-source Agent runtime behind this case.":
    "查看这个案例背后的开源 Agent runtime。",
  "Mosoo source": "Mosoo 源码",
  "See the application compute used by the production deployment.":
    "查看生产部署使用的应用计算能力。",
  "Cloudflare Containers": "Cloudflare Containers",
  "See how durable per-user records are enforced at the database layer.":
    "了解数据库层如何强制执行持久、按用户隔离的记录。",
  "Supabase Row Level Security": "Supabase Row Level Security",
  "Embed an Agent in your own SaaS.": "在你的 SaaS 中嵌入 Agent。",
  "Keep your product, auth, and database. Let mosoo own the Agent lifecycle, isolation, harness, and delegated tool context.":
    "保留你的产品、身份系统和数据库，让 mosoo 负责 Agent 生命周期、隔离、harness 与委托工具上下文。",
} as const;

type Message = keyof typeof ZH_MESSAGES;

const JA_MESSAGES = {
  "Use cases": "ユースケース",
  "Built on mosoo.": "mosoo でつくられたもの。",
  "Real products that publish an Agent once and let any client call it as an API. Each case ships with the repository, the live app, and the integration path.":
    "Agent を一度公開し、任意のクライアントから API として呼び出せるようにした実プロダクト。各ケースにはリポジトリ、ライブアプリ、統合の手順が付属します。",
  "Real products that use mosoo as their Agent backend. Each case shows the live product, the value mosoo provides, and the integration path.":
    "mosoo を Agent backend として使う実プロダクト。各ケースでは、ライブプロダクト、mosoo が提供する価値、統合経路を紹介します。",
  "A production fitness app where users log meals and workouts in natural language. One shared mosoo Agent turns every conversation into isolated, persistent user data.":
    "食事やトレーニングを自然言語で記録できる本番フィットネスアプリ。共有された 1 つの mosoo Agent が、各会話を隔離された永続ユーザーデータに変換します。",
  "The Go Gym dashboard after the Agent recorded a day of meals and training.":
    "Agent が 1 日分の食事とトレーニングを記録した後の Go Gym ダッシュボード。",
  "Upload one avatar and get back a validated ZIP with all nine Codex pet animation states — generated by one published mosoo Agent behind a Cloudflare Worker.":
    "アバターを 1 枚アップロードすると、9 つの Codex ペットアニメーション状態を収めた検証済み ZIP が返ります。Cloudflare Worker の背後で、公開済みの mosoo Agent 1 つが生成します。",
  "Read the case": "ケースを見る",
  "The Codex Pet app: one avatar in, nine animation states out.":
    "Codex Pet アプリ：アバター 1 枚から、9 つのアニメーション状態へ。",
  "More cases are being written up.": "さらに多くのケースを準備中です。",
  "Shipping something on mosoo? We want the next case to be yours.":
    "mosoo で何かをつくっていますか？次のケースはあなたの番です。",
  "Start on mosoo Cloud": "mosoo Cloud で始める",
  "Use case": "ユースケース",
  "Submitted by": "投稿者",
  "Publish one Agent. Let any Codex call it.":
    "Agent を一度公開すれば、どの Codex からでも呼び出せる。",
  "Codex Pet shows how a workflow built in a coding IDE becomes a reusable mosoo-managed Agent exposed through an API — one uploaded avatar comes back as a validated ZIP with all nine Codex pet animation states.":
    "Codex Pet は、coding IDE で組んだワークフローが mosoo 管理の再利用可能な Agent となり、API として公開される様子を示します。アップロードした 1 枚のアバターが、9 つの Codex ペットアニメーション状態を収めた検証済み ZIP になって返ります。",
  "Open the live app": "ライブアプリを開く",
  "View the repository": "リポジトリを見る",
  "How it works": "しくみ",
  "Publish the Agent": "Agent を公開する",
  "A Pet Agent with an avatar-generation skill is published on mosoo. Its environment carries the openai and pillow packages plus an OpenAI provider credential.":
    "アバター生成 skill を持つ Pet Agent を mosoo で公開します。environment には openai と pillow のパッケージ、OpenAI provider の資格情報を設定します。",
  "Copy the Instruction for LLM": "Instruction for LLM をコピーする",
  "Publishing generates an Instruction for LLM — an API contract sized for a prompt. Paste it into Codex and the integration work moves to the coding agent.":
    "公開すると Instruction for LLM が生成されます。プロンプトに収まるサイズの API 契約です。Codex に貼り付ければ、統合作業は coding agent の仕事になります。",
  "Integrate from Codex": "Codex から統合する",
  "Codex wires the mosoo Thread API into the product backend: the Worker creates a Thread with the uploaded avatar, polls the Run, and streams the finished ZIP back.":
    "Codex が mosoo Thread API をプロダクトのバックエンドに接続します。Worker がアップロードされたアバターで Thread を作成し、Run をポーリングして、完成した ZIP をストリーミングで返します。",
  "The request path": "リクエスト経路",
  "The token stays in the Worker. The browser only ever sees the finished ZIP.":
    "token は Worker の中に留まり、ブラウザに渡るのは完成した ZIP だけです。",
  "Watch the 57-second demo": "57 秒のデモを見る",
  "Agent as API, end to end — from publishing the Agent to the downloaded pet.":
    "Agent as API の一部始終 — Agent の公開からペットのダウンロードまで。",
  "What comes out": "得られるもの",
  "A 1536×1872 RGBA WebP atlas with nine animation rows, QA-checked in the sandbox before download.":
    "9 行のアニメーションを収めた 1536×1872 の RGBA WebP アトラス。ダウンロード前に sandbox 内で QA 済みです。",
  Stack: "スタック",
  "Build your own Agent as API.": "あなたの Agent as API をつくる。",
  "Publish an Agent on mosoo, hand its Instruction for LLM to a coding agent, and ship the integration in an afternoon.":
    "mosoo で Agent を公開し、その Instruction for LLM を coding agent に渡せば、統合は半日で出荷できます。",
  "Read the docs": "ドキュメントを読む",
  "One Agent for every user. Their data stays isolated.":
    "1 つの Agent をすべてのユーザーへ。データは互いに隔離。",
  "Go Gym is a production fitness tracker. Users describe meals, workouts, and body measurements in chat; the app turns them into structured records, durable dashboards, and progress summaries.":
    "Go Gym は本番運用されるフィットネストラッカーです。ユーザーがチャットで食事、トレーニング、身体測定を伝えると、アプリが構造化レコード、永続ダッシュボード、進捗サマリーに変換します。",
  "Read the API docs": "API ドキュメントを読む",
  "One Agent, user-scoped Threads": "1 つの Agent、ユーザー単位の Thread",
  "Go Gym publishes one shared Agent. Its trusted backend creates a separate Thread with userId for each signed-in user, so the browser never receives a mosoo token.":
    "Go Gym は共有 Agent を 1 つ公開します。信頼されたバックエンドがログインユーザーごとに userId 付きの個別 Thread を作成するため、ブラウザが mosoo token を受け取ることはありません。",
  "Delegated tool identity": "委任されたツール ID",
  "Mosoo carries the verified user context into the MCP call. The model cannot choose another user ID, while Go Gym and Supabase still enforce authorization at the data boundary.":
    "Mosoo は検証済みのユーザーコンテキストを MCP 呼び出しへ渡します。モデルは別のユーザー ID を選べず、Go Gym と Supabase はデータ境界で引き続き認可を適用します。",
  "Isolated, harness-neutral execution": "隔離された harness 非依存の実行",
  "Each Thread runs in a Cattle sandbox. Production uses OpenCode, while the same business MCP path was verified with Codex and Claude without rewriting the app.":
    "各 Thread は Cattle sandbox で実行されます。本番は OpenCode を使い、同じ業務 MCP 経路をアプリの書き換えなしで Codex と Claude でも検証しました。",
  "Production smoke test": "本番 smoke test",
  "From one message to durable records": "1 件のメッセージから永続レコードへ",
  "A test user described breakfast, lunch, and 45 minutes of strength training in one message. The Agent created three user-scoped records and refreshed the dashboard.":
    "テストユーザーが 1 件のメッセージで朝食、昼食、45 分間の筋力トレーニングを伝えました。Agent はユーザー範囲のレコードを 3 件作成し、ダッシュボードを更新しました。",
  "Verified result": "検証結果",
  "3 structured records": "3 件の構造化レコード",
  "1,150 kcal intake": "摂取 1,150 kcal",
  "64 g protein": "たんぱく質 64 g",
  "320 kcal training burn": "トレーニング消費 320 kcal",
  "What mosoo provides": "mosoo が提供するもの",
  "The production request path": "本番リクエスト経路",
  "The app and Agent runtime are deployed separately. The browser talks only to Go Gym; its backend holds the Mosoo token and supplies the trusted userId.":
    "アプリと Agent runtime は別々にデプロイされます。ブラウザは Go Gym とのみ通信し、バックエンドが Mosoo token を保持して信頼済み userId を渡します。",
  "Mosoo delegates identity; it does not replace application authorization. Go Gym validates the caller and Supabase RLS remains the final data boundary.":
    "Mosoo は ID を委任しますが、アプリの認可を置き換えません。Go Gym が呼び出し元を検証し、Supabase RLS が最終的なデータ境界になります。",
  "Clear ownership across the stack": "スタック全体の明確な責務",
  "Product UI, Supabase login, domain rules, WebSocket updates, and the business tool endpoints.":
    "プロダクト UI、Supabase ログイン、ドメインルール、WebSocket 更新、業務ツールのエンドポイント。",
  "Agent publication, Thread and Run lifecycle, user delegation, sandbox isolation, and harness selection.":
    "Agent の公開、Thread と Run のライフサイクル、ユーザー委任、sandbox 隔離、harness 選択。",
  "OAuth identity, Postgres persistence, Row Level Security, and private file storage.":
    "OAuth ID、Postgres 永続化、Row Level Security、プライベートファイルストレージ。",
  "A stateless Container for the web app and a Worker for the remote MCP service. Durable user data stays in Supabase.":
    "Web アプリはステートレス Container、リモート MCP サービスは Worker で実行します。永続ユーザーデータは Supabase に保存されます。",
  "One use case, multiple harnesses": "1 つのユースケース、複数の harness",
  "Go Gym runs on OpenCode in production. The same Agent contract and business MCP were also exercised through Codex and Claude before release.":
    "Go Gym の本番環境は OpenCode で動作します。同じ Agent 契約と業務 MCP は、リリース前に Codex と Claude でも検証されました。",
  "Published Go Gym Agents for OpenCode, Codex, and Claude in the Mosoo console.":
    "Mosoo コンソールで公開された OpenCode、Codex、Claude 向け Go Gym Agent。",
  "Explore the product and stack": "プロダクトとスタックを見る",
  "Use the production app and try a meal or workout log.":
    "本番アプリで食事やトレーニングを記録してみる。",
  "Try Go Gym": "Go Gym を試す",
  "Create Threads and Runs from an application backend.":
    "アプリケーションバックエンドから Thread と Run を作成する。",
  "Thread API reference": "Thread API リファレンス",
  "Inspect the open-source Agent runtime behind this case.":
    "このケースを支えるオープンソース Agent runtime を確認する。",
  "Mosoo source": "Mosoo ソース",
  "See the application compute used by the production deployment.":
    "本番デプロイで使われるアプリケーション compute を確認する。",
  "Cloudflare Containers": "Cloudflare Containers",
  "See how durable per-user records are enforced at the database layer.":
    "永続的なユーザー別レコードをデータベース層で強制する方法を見る。",
  "Supabase Row Level Security": "Supabase Row Level Security",
  "Embed an Agent in your own SaaS.": "自分の SaaS に Agent を組み込む。",
  "Keep your product, auth, and database. Let mosoo own the Agent lifecycle, isolation, harness, and delegated tool context.":
    "プロダクト、auth、データベースはそのままに。Agent のライフサイクル、隔離、harness、委任ツールコンテキストは mosoo に任せます。",
} satisfies Record<Message, string>;

const MESSAGES = { zh: ZH_MESSAGES, ja: JA_MESSAGES };

export function t(message: Message): string {
  return locale === "en" ? message : MESSAGES[locale][message];
}
