import { locale } from "@/shared/locale";

import { t } from "./i18n";

export interface UseCase {
  author: { avatar: string; name: string };
  detailPath: string;
  image: string;
  imageAlt: string;
  kicker: string;
  name: string;
  productUrl: string;
  repoUrl: string;
  summary: string;
  tags: readonly string[];
}

export const CODEX_PET: UseCase = {
  author: { avatar: "/brand/brand-mark.svg", name: "Mosoo Team" },
  detailPath: `/${locale}/use-cases/codex-pet`,
  image: "/landing/use-cases/codex-pet-app.png",
  imageAlt: t("The Codex Pet app: one avatar in, nine animation states out."),
  kicker: "Agent as API",
  name: "Codex Pet",
  productUrl: "https://app-01kwc37q6ejfnjvvk3g192x5x7.apps.mosoo.ai/",
  repoUrl: "https://github.com/Yevanchen/mosoo-codex-pet",
  summary: t(
    "Upload one avatar and get back a validated ZIP with all nine Codex pet animation states — generated by one published mosoo Agent behind a Cloudflare Worker.",
  ),
  tags: ["Codex", "Thread API", "Cloudflare Worker"],
};

export const CODEX_PET_DEMO_VIDEO = "/landing/use-cases/codex-pet-demo.mp4";
export const CODEX_PET_DEMO_POSTER = "/landing/use-cases/codex-pet-demo.jpg";

export const USE_CASES: readonly UseCase[] = [CODEX_PET];
