// GENERATED by tools/soft-fluid/src/site-covers/integrate.mjs — do not edit by hand.
import type { CoverTimeline } from "../runtime";
import journeyImagineIf from "./journey-imagine-if";
import headlessAgentApi from "./headless-agent-api";
import responsesToAgents from "./responses-to-agents";
import stateNotProcess from "./state-not-process";
import apiCliSkill from "./api-cli-skill";
import ghfindEvaluation from "./ghfind-evaluation";
import petAndCattle from "./pet-and-cattle";
import cloudAgentsFuture from "./cloud-agents-future";
import mosooComputer from "./mosoo-computer";
import humanTimeBeyondExpectations from "./human-time-beyond-expectations";

export const TIMELINES: Record<string, CoverTimeline> = {
  "journey-imagine-if": journeyImagineIf,
  "headless-agent-api": headlessAgentApi,
  "responses-to-agents": responsesToAgents,
  "state-not-process": stateNotProcess,
  "api-cli-skill": apiCliSkill,
  "ghfind-evaluation": ghfindEvaluation,
  "pet-and-cattle": petAndCattle,
  "cloud-agents-future": cloudAgentsFuture,
  "mosoo-computer": mosooComputer,
  "human-time-beyond-expectations": humanTimeBeyondExpectations,
};
