// GENERATED by tools/soft-fluid/src/site-covers/integrate.mjs from manifests/site-covers.json — do not edit by hand.
// Live covers: inline SVG (native text, site fonts) over a baked material raster,
// animated by `runtime.ts` with Motion. Timelines are authored in ./timelines.
import journeyImagineIfSvg from "./generated/journey-imagine-if.svg?raw";
import headlessAgentApiSvg from "./generated/headless-agent-api.svg?raw";
import responsesToAgentsSvg from "./generated/responses-to-agents.svg?raw";
import stateNotProcessSvg from "./generated/state-not-process.svg?raw";
import apiCliSkillSvg from "./generated/api-cli-skill.svg?raw";
import ghfindEvaluationSvg from "./generated/ghfind-evaluation.svg?raw";
import petAndCattleSvg from "./generated/pet-and-cattle.svg?raw";
import cloudAgentsFutureSvg from "./generated/cloud-agents-future.svg?raw";
import mosooComputerSvg from "./generated/mosoo-computer.svg?raw";
import humanTimeBeyondExpectationsSvg from "./generated/human-time-beyond-expectations.svg?raw";

type Locale = "en" | "zh" | "ja";

export interface CoverEntry {
  svg: string;
  /** Root-absolute URL of the baked background (stage, bloom, grain, shadows). */
  material: string;
  /** Page colour behind the material while it loads. */
  ground: string;
  /** Names of the timeline stages, shown next to the play controls. */
  stages: Record<Locale, readonly string[]>;
}

export const COVERS = {
  "journey-imagine-if": {
    svg: journeyImagineIfSvg,
    material: "/blog/blog/the-journey-begins-with-an-imagine-if/cover-material.webp",
    ground: "#F4F3EC",
    stages: {"en":["One-off","Threshold","Lifecycle"],"zh":["一次性交付","阈值","生命周期"],"ja":["単発の納品","しきい値","ライフサイクル"]},
  },
  "headless-agent-api": {
    svg: headlessAgentApiSvg,
    material: "/blog/blog/why-we-need-a-headless-agent-api-in-the-cloud/cover-material.webp",
    ground: "#DEDFD7",
    stages: {"en":["Submitted","Running","Result"],"zh":["已提交","执行中","产出"],"ja":["送信済み","実行中","成果物"]},
  },
  "responses-to-agents": {
    svg: responsesToAgentsSvg,
    material: "/blog/blog/from-responses-to-agents/cover-material.webp",
    ground: "#DEDFD7",
    stages: {"en":["Response","State + tools","Agents"],"zh":["响应","状态与工具","Agents"],"ja":["レスポンス","状態とツール","Agents"]},
  },
  "state-not-process": {
    svg: stateNotProcessSvg,
    material: "/blog/blog/agent-state-is-not-process-state/cover-material.webp",
    ground: "#252824",
    stages: {"en":["Running","Process gone","Next run"],"zh":["运行中","进程消失","下一次运行"],"ja":["実行中","プロセス消失","次の実行"]},
  },
  "api-cli-skill": {
    svg: apiCliSkillSvg,
    material: "/blog/blog/api-cli-skill-development-paradigm/cover-material.webp",
    ground: "#F4F3EC",
    stages: {"en":["API + spec","CLI + tests","Repeat"],"zh":["API 与规范","CLI 与测试","循环"],"ja":["API と仕様","CLI とテスト","繰り返し"]},
  },
  "ghfind-evaluation": {
    svg: ghfindEvaluationSvg,
    material: "/blog/blog/ghfind-mosoo-project-evaluation/cover-material.webp",
    ground: "#141713",
    stages: {"en":["Repository","Evaluation","Judgment"],"zh":["提交仓库","评估","结构化判断"],"ja":["リポジトリ","評価","判断"]},
  },
  "pet-and-cattle": {
    svg: petAndCattleSvg,
    material: "/blog/blog/two-kinds-of-agents-pet-and-cattle/cover-material.webp",
    ground: "#F4F3EC",
    stages: {"en":["Cultivated","Replaced","Both"],"zh":["培养","替换","两种期待"],"ja":["育てる","入れ替える","二つの期待"]},
  },
  "cloud-agents-future": {
    svg: cloudAgentsFutureSvg,
    material: "/blog/blog/when-cloud-agents-become-the-future/cover-material.webp",
    ground: "#141713",
    stages: {"en":["Address","Environment","Run"],"zh":["地址","Environment","Run"],"ja":["アドレス","Environment","Run"]},
  },
  "mosoo-computer": {
    svg: mosooComputerSvg,
    material: "/blog/blog/introducing-mosoo-computer/cover-material.webp",
    ground: "#DEDFD7",
    stages: {"en":["Awake","Sleeping","Woken"],"zh":["运行中","休眠","被唤醒"],"ja":["稼働中","スリープ","復帰"]},
  },
  "human-time-beyond-expectations": {
    svg: humanTimeBeyondExpectationsSvg,
    material: "/blog/blog/human-time-beyond-expectations/cover-material.webp",
    ground: "#F4F3EC",
    stages: {"en":["Hidden","Revealing","Seen / unseen"],"zh":["遮住","揭开","可见与不可见"],"ja":["隠れる","見えてくる","見える・見えない"]},
  },
} satisfies Record<string, CoverEntry>;

export type CoverId = keyof typeof COVERS;

export function getCover(id: string | undefined): (CoverEntry & { id: CoverId }) | undefined {
  if (!id || !(id in COVERS)) return undefined;
  return { id: id as CoverId, ...COVERS[id as CoverId] };
}
