// Manifest-driven integration. Builds selected new covers, preserves old assets,
// regenerates the complete registry, and changes only declared hero fields.
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const kit = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
const manifest = JSON.parse(readFileSync(join(kit, "manifests/site-covers.json"), "utf8"));
const args = Object.fromEntries(process.argv.slice(2).map((a) => a.replace(/^--/, "").split("=")).map(([k, v]) => [k, v ?? true]));
const site = resolve(kit, args.site ?? manifest.site);
if (!args.only || typeof args.only !== "string") throw new Error("Pass --only=<id>; this kit never rebuilds all covers implicitly.");
const selectedIds = args.only.split(",");
const covers = selectedIds.map((id) => {
  const cover = manifest.covers.find((c) => c.id === id);
  if (!cover?.module) throw new Error(`No local authoring source for ${id}; historical covers are metadata-only here.`);
  return cover;
});
const camel = (id) => id.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());

for (const cover of covers) {
  const out = execFileSync(process.execPath, [join(kit, "src/site-covers/build-site-cover.mjs"), cover.module, site], { cwd: kit, encoding: "utf8" });
  console.log(out.trim());
}

// Missing old assets are an error, rather than silently dropping an old entry.
const live = manifest.covers.filter((c) => c.slug);
for (const cover of live) {
  for (const file of [`generated/${cover.id}.svg`, `timelines/${cover.id}.ts`]) {
    if (!existsSync(join(site, "apps/blog/src/covers", file))) throw new Error(`Missing registered cover file: ${file}`);
  }
}
const registry = `// GENERATED by tools/soft-fluid/src/site-covers/integrate.mjs from manifests/site-covers.json — do not edit by hand.
// Live covers: inline SVG (native text, site fonts) over a baked material raster,
// animated by \`runtime.ts\` with Motion. Timelines are authored in ./timelines.
${live.map((c) => `import ${camel(c.id)}Svg from "./generated/${c.id}.svg?raw";`).join("\n")}

type Locale = "en" | "zh" | "ja";

export interface CoverEntry {
  svg: string;
  /** Root-absolute URL of the baked background (stage, bloom, grain, shadows). */
  material: string;
  /** Page colour behind the material while it loads. */
  ground: string;
  /** Names of the timeline stages, shown next to the play controls. */
  stages: Record<Locale, readonly string[]>;
}

export const COVERS = {
${live.map((c) => `  ${JSON.stringify(c.id)}: {
    svg: ${camel(c.id)}Svg,
    material: "/blog/blog/${c.slug}/cover-material.webp",
    ground: ${JSON.stringify(c.ground)},
    stages: ${JSON.stringify(c.stages)},
  },`).join("\n")}
} satisfies Record<string, CoverEntry>;

export type CoverId = keyof typeof COVERS;

export function getCover(id: string | undefined): (CoverEntry & { id: CoverId }) | undefined {
  if (!id || !(id in COVERS)) return undefined;
  return { id: id as CoverId, ...COVERS[id as CoverId] };
}
`;
writeFileSync(join(site, "apps/blog/src/covers/registry.ts"), registry);
writeFileSync(join(site, "apps/blog/src/covers/timelines/index.ts"), `// GENERATED by tools/soft-fluid/src/site-covers/integrate.mjs — do not edit by hand.
import type { CoverTimeline } from "../runtime";
${live.map((c) => `import ${camel(c.id)} from "./${c.id}";`).join("\n")}

export const TIMELINES: Record<string, CoverTimeline> = {
${live.map((c) => `  ${JSON.stringify(c.id)}: ${camel(c.id)},`).join("\n")}
};
`);

for (const cover of covers) {
  for (const locale of cover.locales ?? ["en", "zh", "ja"]) {
    const suffix = locale === "en" ? "" : `-${locale}`;
    const file = join(site, "apps/blog/src/content/blog", `${cover.slug}${suffix}.mdx`);
    const raw = readFileSync(file, "utf8");
    const match = raw.match(/^---\n([\s\S]*?)\n---([\s\S]*)$/);
    if (!match) throw new Error(`Invalid frontmatter: ${file}`);
    const [, fm, body] = match;
    const lines = fm.split("\n").filter((line) => !/^heroCover:/.test(line));
    const set = (key, value) => {
      const index = lines.findIndex((line) => line.startsWith(`${key}:`));
      const next = `${key}: ${JSON.stringify(value)}`;
      if (index >= 0) lines[index] = next;
      else lines.push(next);
    };
    if (!cover.alt[locale]) throw new Error(`Missing ${locale} alt for ${cover.id}`);
    set("heroImage", `/blog/blog/${cover.slug}/cover.jpg`);
    set("heroAlt", cover.alt[locale]);
    const altIndex = lines.findIndex((line) => line.startsWith("heroAlt:"));
    lines.splice(altIndex + 1, 0, `heroCover: ${JSON.stringify(cover.id)}`);
    const next = `---\n${lines.join("\n")}\n---${body}`;
    if (next !== raw) writeFileSync(file, next);
  }
  console.log(`integrated ${cover.id}: ${(cover.locales ?? ["en", "zh", "ja"]).join(", ")}`);
}
